// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: pokerreferee.proto

package pokerrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PokerReferee_OpenEscrow_FullMethodName        = "/poker.PokerReferee/OpenEscrow"
	PokerReferee_BindEscrow_FullMethodName        = "/poker.PokerReferee/BindEscrow"
	PokerReferee_PublishSessionKey_FullMethodName = "/poker.PokerReferee/PublishSessionKey"
	PokerReferee_SettlementStream_FullMethodName  = "/poker.PokerReferee/SettlementStream"
	PokerReferee_GetFinalizeBundle_FullMethodName = "/poker.PokerReferee/GetFinalizeBundle"
	PokerReferee_GetEscrowStatus_FullMethodName   = "/poker.PokerReferee/GetEscrowStatus"
	PokerReferee_SetPayoutAddress_FullMethodName  = "/poker.PokerReferee/SetPayoutAddress"
)

// PokerRefereeClient is the client API for PokerReferee service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PokerReferee coordinates Schnorr adaptor escrow/presign/finalize for
// SNG/WTA tables (2–6 seats, single winner).
type PokerRefereeClient interface {
	// Creates a per-player escrow session for a table/session/seat.
	OpenEscrow(ctx context.Context, in *OpenEscrowRequest, opts ...grpc.CallOption) (*OpenEscrowResponse, error)
	// Binds an existing escrow to a table/session seat and reports readiness.
	BindEscrow(ctx context.Context, in *BindEscrowRequest, opts ...grpc.CallOption) (*BindEscrowResponse, error)
	// Publishes the compressed session pubkey used for adaptor presign.
	PublishSessionKey(ctx context.Context, in *PublishSessionKeyRequest, opts ...grpc.CallOption) (*PublishSessionKeyResponse, error)
	// Bidirectional stream for presign handshakes (HELLO → REQ → presigs).
	SettlementStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SettlementStreamMessage, SettlementStreamMessage], error)
	// Returns the draft, gamma, and presigs for the winning branch.
	GetFinalizeBundle(ctx context.Context, in *GetFinalizeBundleRequest, opts ...grpc.CallOption) (*GetFinalizeBundleResponse, error)
	// Returns funding/conf status for an escrow owned by the caller.
	GetEscrowStatus(ctx context.Context, in *GetEscrowStatusRequest, opts ...grpc.CallOption) (*GetEscrowStatusResponse, error)
	SetPayoutAddress(ctx context.Context, in *SetPayoutAddressRequest, opts ...grpc.CallOption) (*SetPayoutAddressResponse, error)
}

type pokerRefereeClient struct {
	cc grpc.ClientConnInterface
}

func NewPokerRefereeClient(cc grpc.ClientConnInterface) PokerRefereeClient {
	return &pokerRefereeClient{cc}
}

func (c *pokerRefereeClient) OpenEscrow(ctx context.Context, in *OpenEscrowRequest, opts ...grpc.CallOption) (*OpenEscrowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenEscrowResponse)
	err := c.cc.Invoke(ctx, PokerReferee_OpenEscrow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerRefereeClient) BindEscrow(ctx context.Context, in *BindEscrowRequest, opts ...grpc.CallOption) (*BindEscrowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindEscrowResponse)
	err := c.cc.Invoke(ctx, PokerReferee_BindEscrow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerRefereeClient) PublishSessionKey(ctx context.Context, in *PublishSessionKeyRequest, opts ...grpc.CallOption) (*PublishSessionKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishSessionKeyResponse)
	err := c.cc.Invoke(ctx, PokerReferee_PublishSessionKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerRefereeClient) SettlementStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SettlementStreamMessage, SettlementStreamMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PokerReferee_ServiceDesc.Streams[0], PokerReferee_SettlementStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SettlementStreamMessage, SettlementStreamMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PokerReferee_SettlementStreamClient = grpc.BidiStreamingClient[SettlementStreamMessage, SettlementStreamMessage]

func (c *pokerRefereeClient) GetFinalizeBundle(ctx context.Context, in *GetFinalizeBundleRequest, opts ...grpc.CallOption) (*GetFinalizeBundleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFinalizeBundleResponse)
	err := c.cc.Invoke(ctx, PokerReferee_GetFinalizeBundle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerRefereeClient) GetEscrowStatus(ctx context.Context, in *GetEscrowStatusRequest, opts ...grpc.CallOption) (*GetEscrowStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEscrowStatusResponse)
	err := c.cc.Invoke(ctx, PokerReferee_GetEscrowStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerRefereeClient) SetPayoutAddress(ctx context.Context, in *SetPayoutAddressRequest, opts ...grpc.CallOption) (*SetPayoutAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPayoutAddressResponse)
	err := c.cc.Invoke(ctx, PokerReferee_SetPayoutAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PokerRefereeServer is the server API for PokerReferee service.
// All implementations must embed UnimplementedPokerRefereeServer
// for forward compatibility.
//
// PokerReferee coordinates Schnorr adaptor escrow/presign/finalize for
// SNG/WTA tables (2–6 seats, single winner).
type PokerRefereeServer interface {
	// Creates a per-player escrow session for a table/session/seat.
	OpenEscrow(context.Context, *OpenEscrowRequest) (*OpenEscrowResponse, error)
	// Binds an existing escrow to a table/session seat and reports readiness.
	BindEscrow(context.Context, *BindEscrowRequest) (*BindEscrowResponse, error)
	// Publishes the compressed session pubkey used for adaptor presign.
	PublishSessionKey(context.Context, *PublishSessionKeyRequest) (*PublishSessionKeyResponse, error)
	// Bidirectional stream for presign handshakes (HELLO → REQ → presigs).
	SettlementStream(grpc.BidiStreamingServer[SettlementStreamMessage, SettlementStreamMessage]) error
	// Returns the draft, gamma, and presigs for the winning branch.
	GetFinalizeBundle(context.Context, *GetFinalizeBundleRequest) (*GetFinalizeBundleResponse, error)
	// Returns funding/conf status for an escrow owned by the caller.
	GetEscrowStatus(context.Context, *GetEscrowStatusRequest) (*GetEscrowStatusResponse, error)
	SetPayoutAddress(context.Context, *SetPayoutAddressRequest) (*SetPayoutAddressResponse, error)
	mustEmbedUnimplementedPokerRefereeServer()
}

// UnimplementedPokerRefereeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPokerRefereeServer struct{}

func (UnimplementedPokerRefereeServer) OpenEscrow(context.Context, *OpenEscrowRequest) (*OpenEscrowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OpenEscrow not implemented")
}
func (UnimplementedPokerRefereeServer) BindEscrow(context.Context, *BindEscrowRequest) (*BindEscrowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BindEscrow not implemented")
}
func (UnimplementedPokerRefereeServer) PublishSessionKey(context.Context, *PublishSessionKeyRequest) (*PublishSessionKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishSessionKey not implemented")
}
func (UnimplementedPokerRefereeServer) SettlementStream(grpc.BidiStreamingServer[SettlementStreamMessage, SettlementStreamMessage]) error {
	return status.Error(codes.Unimplemented, "method SettlementStream not implemented")
}
func (UnimplementedPokerRefereeServer) GetFinalizeBundle(context.Context, *GetFinalizeBundleRequest) (*GetFinalizeBundleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFinalizeBundle not implemented")
}
func (UnimplementedPokerRefereeServer) GetEscrowStatus(context.Context, *GetEscrowStatusRequest) (*GetEscrowStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEscrowStatus not implemented")
}
func (UnimplementedPokerRefereeServer) SetPayoutAddress(context.Context, *SetPayoutAddressRequest) (*SetPayoutAddressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPayoutAddress not implemented")
}
func (UnimplementedPokerRefereeServer) mustEmbedUnimplementedPokerRefereeServer() {}
func (UnimplementedPokerRefereeServer) testEmbeddedByValue()                      {}

// UnsafePokerRefereeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PokerRefereeServer will
// result in compilation errors.
type UnsafePokerRefereeServer interface {
	mustEmbedUnimplementedPokerRefereeServer()
}

func RegisterPokerRefereeServer(s grpc.ServiceRegistrar, srv PokerRefereeServer) {
	// If the following call panics, it indicates UnimplementedPokerRefereeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PokerReferee_ServiceDesc, srv)
}

func _PokerReferee_OpenEscrow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenEscrowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerRefereeServer).OpenEscrow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PokerReferee_OpenEscrow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerRefereeServer).OpenEscrow(ctx, req.(*OpenEscrowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokerReferee_BindEscrow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindEscrowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerRefereeServer).BindEscrow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PokerReferee_BindEscrow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerRefereeServer).BindEscrow(ctx, req.(*BindEscrowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokerReferee_PublishSessionKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishSessionKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerRefereeServer).PublishSessionKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PokerReferee_PublishSessionKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerRefereeServer).PublishSessionKey(ctx, req.(*PublishSessionKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokerReferee_SettlementStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PokerRefereeServer).SettlementStream(&grpc.GenericServerStream[SettlementStreamMessage, SettlementStreamMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PokerReferee_SettlementStreamServer = grpc.BidiStreamingServer[SettlementStreamMessage, SettlementStreamMessage]

func _PokerReferee_GetFinalizeBundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFinalizeBundleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerRefereeServer).GetFinalizeBundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PokerReferee_GetFinalizeBundle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerRefereeServer).GetFinalizeBundle(ctx, req.(*GetFinalizeBundleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokerReferee_GetEscrowStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEscrowStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerRefereeServer).GetEscrowStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PokerReferee_GetEscrowStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerRefereeServer).GetEscrowStatus(ctx, req.(*GetEscrowStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokerReferee_SetPayoutAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPayoutAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerRefereeServer).SetPayoutAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PokerReferee_SetPayoutAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerRefereeServer).SetPayoutAddress(ctx, req.(*SetPayoutAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PokerReferee_ServiceDesc is the grpc.ServiceDesc for PokerReferee service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PokerReferee_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "poker.PokerReferee",
	HandlerType: (*PokerRefereeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenEscrow",
			Handler:    _PokerReferee_OpenEscrow_Handler,
		},
		{
			MethodName: "BindEscrow",
			Handler:    _PokerReferee_BindEscrow_Handler,
		},
		{
			MethodName: "PublishSessionKey",
			Handler:    _PokerReferee_PublishSessionKey_Handler,
		},
		{
			MethodName: "GetFinalizeBundle",
			Handler:    _PokerReferee_GetFinalizeBundle_Handler,
		},
		{
			MethodName: "GetEscrowStatus",
			Handler:    _PokerReferee_GetEscrowStatus_Handler,
		},
		{
			MethodName: "SetPayoutAddress",
			Handler:    _PokerReferee_SetPayoutAddress_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SettlementStream",
			Handler:       _PokerReferee_SettlementStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pokerreferee.proto",
}
